### ISSUE TITLE
[Bug Report] Cannot launch on flashcard 

### ISSUE THREAD

**Issue by Marvo995** [Universal-Team/pkmn-chest#18]
My flashcard gives me an error message  while trying to open the app. 
I put the  .nds pkmnchest file on the root folder of the micro SD card with the pokemon game save files; I Booted my flashcard ( a R4 SDHC Dual Core 2017 model, one of the many R4 clones) and after selecting the  .nds pkmnchest, the loading bar stops and the error message "load rom errorcode=-4" shows up. 
I tried different releases, but nothing changes,it's probably something wrong with how I place the files (maybe they must be put in a specific sub-folder?) or with the flashcard itself or my console (I run the flashcard on my 2DS in DS mode).

 I hope I have given enough information to make my issue clear.

**Comment by FlameKat53** [comment]
pkmn-chest doesn’t work with YSMenu

**Comment by Epicpkmn11** [comment]
You should be able to launch it if you run it from [nds-hb-menu](https://github.com/devkitPro/nds-hb-menu/releases), I'll look into fixing this but I'm not sure if I'm able to while keeping proper compatibility with TWiLight Menu++ on DSi/3DS as modern "DSi-Enhanced" homebrew are identified as retail games by YSMenu

**Comment by Marvo995** [comment]
Actually I am just using the R4 kernel, but YS Menu gives me the exact same message. At this point I think They probably share the same infrastructure. Isn't there an alternate launcher I can run pkmnchest with?

**Comment by Marvo995** [comment]
It properly boots up with Hbmenu, thank you so much for the fast help.

**Comment by Epicpkmn11** [comment]
If you wouldn't mind could you try [this](https://github.com/Universal-Team/extras/releases/tag/v20190819-185117) new build on your flashcard to make sure it works? It should now work without needing to be launched from HBMenu

**Comment by Marvo995** [comment]
It now works directly from the flashcard kernel (and YS menu as well).

**Comment by Epicpkmn11** [comment]
Nice! @VoltZ tested it on his flashcard and it worked there too so I think it should hopefully work on most flashcards directly now
