### ISSUE TITLE
I can't compile the program

### ISSUE THREAD

**Issue by WinButton43** [Universal-Team/pkmn-chest#29]
Hi, noobie here. When I try to compile the program using "dkp-makepkg Makefile" it says that PKGBUILD does not exist. How do I compile the program.
Looking forward to your reply.
Sergio.

P.D.: I already ran the command "sudo dkp-pacman -S nds-dev".

**Comment by Epicpkmn11** [comment]
Just run `make` in the pkmn-chest source directory, I'm not sure what `dkp-makepkg` does but it's not used for this ;P

**Comment by WinButton43** [comment]
It works, thank you so much!!

**Comment by Epicpkmn11** [comment]
No problem 😃
