### ISSUE TITLE
[Feature Request] Sound Effects! :D 

### ISSUE THREAD

**Issue by SuperSaiyajinVoltZ** [Universal-Team/pkmn-chest#3]
**Is your feature request related to a problem? Please describe.**
It's not related to a Problem. :)

**Describe the solution you'd like**
I would like it, if there are Sound effects, like when you saving a Game. ;D

**Describe alternatives you've considered**
I don't know.. Sound Effects shouldn't be too hard to implement I think. ;)

**Additional context**
Sound Effect Ideas : 
Saving -> The Classic Pokémon Saving Sound or similar Maybe?
Cursor -> Maybe a similar to the Pokémon one?

**Comment by Epicpkmn11** [comment]
No saving sound... but I'm going to call this done with 885053a
