### ISSUE TITLE
Guru meditation error when opening sd card.

### ISSUE THREAD

**Issue by WinButton43** [Universal-Team/pkmn-chest#30]
When I open the app and try to enter to the sd card a red Guru Meditation Error pops up on the bottom screen.
I used HiyaCFW and Twillight Menu++ on my DSi and  I tried using both a Platinum 1GB Mini SD card and a Samsung 16 EVO Micro SD Card.
pc: 020B71A8
addr: 17A9D40A
Thank you for your support
Sergio

**Comment by SuperSaiyajinVoltZ** [comment]
You can also join our Discord Server for support. You will more likely get an answer there in the pkmn-chest channel, because we are more active there. Discord Server invite: https://discord.gg/KDJCfGF

**Comment by Epicpkmn11** [comment]
Is this with a build you did or a release / Azure nightly build?

pkmn-chest has problems with SD access when a cartridge is in when built on Linux computers... I've got no idea why this happens, it's really weird since it only affects Linux...

**Comment by WinButton43** [comment]
Thanks, I took out my flashcart and it worked.
Thanks a lot!
