### ISSUE TITLE
[Bug Report] Newly generated 3 Gen Pokémon have no ability

### ISSUE THREAD

**Issue by Dartz150** [Universal-Team/pkmn-chest#52]
**Describe the bug**
Pokemon end created without any ability.

**To Reproduce**
1. Load a Gen 3 save file.
2. Select an empty space on any box and click "create"
3. Select your desired Species.
4. Save, then load the game, see your Pokémon stats and you'll see that the Pokémon has no ability, it shows "(?)"

**Expected behavior**
Pokemon should have the ability that is shown in Pokémon chest while being created.

**Console (please complete the following information):**
  - [ ] DS/DSi/3DS using a Flashcard
  - [x] DSi (Using SD card)
  - [ ] 3DS (Using SD card)
- Version [v2.0.1]

**Additional context**
Pokemon chest also doesn't let you pick a secondary ability.

**Comment by Epicpkmn11** [comment]
I forgot to add Gen. 3 to the [change ability function](https://github.com/Universal-Team/pkmn-chest/blob/master/arm9/source/menus/summary.cpp#L43), fixed in 2e70792
