### ISSUE TITLE
[Bug Report] CIA Version : Always `Invalid Save File`.

### ISSUE THREAD

**Issue by SuperSaiyajinVoltZ** [Universal-Team/pkmn-chest#6]
**Describe the bug**
I start the CIA and when I want to load a Sav File.. it Always said `Invalid Save File` but the Save is fine.. even Cartridges do the same..

**To Reproduce**
1. start the CIA Version.
2. Try to load a Save. (even Cartridge)
3. `Invalid Save File`.

**Expected behavior**
It should load the Save fine.

**Screenshots**
I don't think it would be useful, because it is only a Message.

**Console (please complete the following information):**
  - [ ] DS/DSi/3DS using a Flashcard
  - [ ] DSi (Using SD card)
  - [ ] 3DS (Using SD card) 
  - [x] 3DS CIA
- Commit : https://github.com/Universal-Team/pkmn-chest/commit/5da6fa3f4c091352cf1851c87eefd08b418f91e2

**Additional context**

**Comment by Epicpkmn11** [comment]
Fixed by #7
