### ISSUE TITLE
[Feature Request] Help with building for JPN Version

### ISSUE THREAD

**Issue by huhu2323** [Universal-Team/pkmn-chest#60]
PKMN CHEST LANGUAGE
So I tried to build PKMN CHEST (https://github.com/Universal-Team/pkmn-chest) with JPN version i8n on english (I basically copied eng to jpn gui.json) because I want to use PKMN CHEST on jpn console but english language. But an error occurred that says:

Guru meditation error
According to this https://github.com/Universal-Team/pkmn-chest/issues/30 issue post, it has a problem building on a linux machine, I dont really have any idea/experience on building it on a windows, tried everything else, cygwin, nmake .. can some help me?

**Comment by Epicpkmn11** [comment]
I assume you figured it out as you closed the issue, but incase anyone finds this in the future looking for the same thing...

You can change the language by pressing <kbd>SELECT</kbd> on the first screen that shows up, then set language to whatever you want, on the wiki there's a page that has the word for "language" in all supported languages: https://github.com/Universal-Team/pkmn-chest/wiki/getting-started#language

**Comment by huhu2323** [comment]
Yeah, I figured it out after building the app. I found the setting, I cant
find it when it was in jpn language, so I assumed its language is based on
console region.
