### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by KaraVsBread** [Universal-Team/pkmn-chest#61]
**Describe the bug**
Loading error. Won't load on a flashcart and emulator gives error "fatInitDefault() failed..."

**To Reproduce**
1. Load the .nds file.

**Expected behavior**
The file to load.

**Screenshots**

**Console (please complete the following information):**
  - [ ] DS/3DS using a Flashcard
  - [ ] DS emulator DeSmuMe
- Version [daily and nightly]

**Additional context**
There isn't anything to add.

**Comment by NightYoshi370** [comment]
What flashcart? What kernel? What launcher?

**Comment by KaraVsBread** [comment]
> What flashcart? What kernel? What launcher?

An R4i SDHC Dual-Core 2020 card, a clone. Generic things on it, R4imenu with Moonshell.

**Comment by NightYoshi370** [comment]
Launch it from TWiLight Menu++ instead.

**Comment by KaraVsBread** [comment]
> Launch it from TWiLight Menu++ instead.

Tried that just now. Rom loads this time, but I get a "Guru Meditation Error!" on a red screen at the bottom.

**Comment by Epicpkmn11** [comment]
Are you using the [latest release](https://github.com/Universal-Team/pkmn-chest/releases/tag/v2.2) or a nightly? The latest nightly is probably broken

**Comment by KaraVsBread** [comment]
> Are you using the [latest release](https://github.com/Universal-Team/pkmn-chest/releases/tag/v2.2) or a nightly? The latest nightly is probably broken
> 
> If you want a nightly [this one](https://github.com/Universal-Team/extras/blob/4d486b50090d193c1eb450c913d120089aec64a9/builds/pkmn-chest/pkmn-chest.nds) is the most likely recent one to work, but I don't remember if it did or not

I think I was using the nightly, I'll try the latest release in a second. Accidentally corrupted the microSD, need to reformat.

**Comment by KaraVsBread** [comment]
All works now, danke!
