### ISSUE TITLE
[Bug Report] NitroFSInit() fails when launching from anywhere that isn't root

### ISSUE THREAD

**Issue by lifehackerhansol** [Universal-Team/pkmn-chest#65]
**Describe the bug**
pkmn-chest simply does not boot if a) it is not in root, or b) not inside `_nds/pkmn-chest`. It throws a NitroFSInit() error and asks to place it somewhere else etc etc
Currently tested on YSMenu, but I recall this happening with TWiLight before, too (though that was a while ago)

**To Reproduce**
1. Place pkmn-chest anywhere that isn't root or in `_nds/pkmn-chest`
2. Boot pkmn-chest
3. See error

**Expected behavior**
It should not complain about where it is placed and just work.

**Screenshots**
https://ibb.co/LvYhKHv
Only happens when not in said location

**Console (please complete the following information):**
  - [x] DS/DSi/3DS using a Flashcard
  - [ ] DSi (Using SD card)
  - [ ] 3DS (Using SD card)
- Version 2.2

**Additional context**
I have not actually tested this while pkmn-chest is extracted, so all of this is tested on first-time setup of pkmn-chest. Even if that works, though, this shouldn't be happening.

**Comment by NightYoshi370** [comment]
Please test this on the latest nightly

**Comment by Epicpkmn11** [comment]
YSMenu doesn't pass argv so it doesn't know where it is outside of root, you can place a copy at `fat:/_nds/pkmn-chest/pkmn-chest.nds` and actually use it anywhere else though. Or you can use TWiLight Menu++/nds-hb-menu, they should work, if they don't then that's a problem.

**Comment by lifehackerhansol** [comment]
I think that should be mentioned in the README somewhere. The error is descriptive, but would rather be warned beforehand (?)

I'll check TWiLight Menu++ in a bit and report back.

**Comment by Epicpkmn11** [comment]
It's on the wiki's [Getting Started page](https://github.com/Universal-Team/pkmn-chest/wiki/getting-started), would probably be good to add to the README too though

**Comment by lifehackerhansol** [comment]
Maybe direct users reading the README to the wiki? It didn't even cross my mind that there was a wiki lmao

Also, it works on TWiLight. Guess that's that.

**Comment by NightYoshi370** [comment]
I guess since this is intended behavior, this should be closed.
