### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by JJRol1** [Universal-Team/pkmn-chest#71]
**Describe the bug**
pkmn-chest will not open on a DS Lite using a r4 card with YSmenu.
I have followed the tutorials for installing it but when launched there's a black screen, and you need to do a hard reboot to restart the system.

**To Reproduce**
I'm not sure if this could be reproduced, and I don't have any steps that could cause it to be reproduced.

**Expected behavior**
I expected pkmn-chest to launch normally.

**Screenshots**
None available

**Console (please complete the following information):**
  - [✔] DS/DSi/3DS using a Flashcard
  - [❌] DSi (Using SD card)
  - [❌] 3DS (Using SD card)
- Version [v2.2]

**Additional context**
None available

**Comment by Epicpkmn11** [comment]
Try loading [TWiLight Menu++](https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard), [nds-hb-menu](https://github.com/devkitPro/nds-hb-menu), or [GodMode9i](https://github.com/DS-Homebrew/GodMode9i/releases) from YSMenu, then load pkmn-chest from there.

**Comment by JJRol1** [comment]
It worked with GodMode9i, thanks!
