### ISSUE TITLE
Deleted save data [Bug Report] 

### ISSUE THREAD

**Issue by AstreaExia** [Universal-Team/pkmn-chest#84]
**Describe the bug**
Physical Cartridge save data deleted when power to system ran out

**To Reproduce**

1. Taking a pokemon from the Heartgold PC box and placing it in chest.
2. Closing chest and on the third bar of saving data  after the changes to the chest were saved and after the first bar stated tge changes to the save file were being saved  when power was lost and or turned off
3. Upon booting back into chest  presented with Invalid save file when selecting Cartridge (but when checking with another game the transfered pokemon is in the chest) 
4. Upon booting directly into the game itself it acts as a new Cartridge with no save file.

**Expected behavior**
That the save file would be intact but the pokemon that was supposed to be move to chest would still be in the games PC.

**Screenshots**

**Console (please complete the following information):**
  - [ ] DSi (Using SD card)
  - Version (2.2-52765cc)

**Comment by Epicpkmn11** [comment]
That is to be expected if power is cut while writing the save. You should have a backup in `sd:/_nds/pkmn-chest/backups/card` iirc

**Comment by AstreaExia** [comment]
Thank you so much it did not occur to me that their was a backup folder to
check you have saved me so much time now that I don't have to restart that
file. Thank you.
