### ISSUE TITLE
[Bug Report] Most alternate form Pokémon's types are broken in gen 5 saves

### ISSUE THREAD

**Issue by Epicpkmn11** [Universal-Team/pkmn-chest#9]
**Describe the bug**
Unown is Poison/Flying in Generation 5

**To Reproduce**
1. Have Unown in Gen 5 (Note: I brought it from 4)

**Expected behavior**
It is Psychic

**Console (please complete the following information):**
  - [ ] DS/DSi/3DS using a Flashcard
  - [x] DSi (Using SD card)
  - [ ] 3DS (Using SD card)
- Version [e.g. v0.1]
~~The commit I'm about to do~~ e189abb

**Additional context**
I don't have an Unown in gen 5, so I only had ones from 4

**Comment by Zayne64** [comment]
Bug is completely random. Transferred a Z form Unown from Platinum to Black and check ingame. It says psychic but is S form? In Pokemon Chest, it says Ground-type!?

It might be the different forms interfereing with the type variable.

**Comment by Epicpkmn11** [comment]
[Note to self]
Unown: `A` is correct, all others have incorrect but real types
Rotom: Normal is correct, all others are type `255`
Giratina: Normal is correct, Origin is `255`
Shaymin: Both are correct
Basculin: Both are correct
Darmanitan: Normal is correct, Zen is wrong
Deerling: Spring is correct, summer/fall are poison, winter is poison/ground
Sawsbuck: All are correct
Melloetta: Both are correct
Tornadus: Normal is correct, alt is `255`
Thunderus: Both are correct
Landorus: Normal is correct, alt is `255`
Kyurem: All are correct
Keldeo: Normal is correct, alt is `255`

---

None of the broken ones types vary between forms (iirc, I didn't check), but some Pokémon who stay the same aren't broken...

**Comment by Epicpkmn11** [comment]
[note to self 2, list of `formSpecies`]
Unown: `A` 201, the others start at `26` and go by one each from there
Rotom: `479`, alts start at `46106`
Giratina: `487`, `45964`
Shaymin: `492`, `690`
Basculin: `550`, `700`
Darmanitan: `555`, `48545`
Deerling: `585`, `32`, `33`, `34`
Sawsbuck: all `586`
Melloetta: `648`, `702`
Tornadus: `641`, `49792`
Thunderus: `642`, `707`
Landorus: `645`, `50301`
Kyurem: `646`, `703`, `704`
Keldeo: `647`, `49562`

---

So it seems that when it's working correctly the `formSpecies` is either the same as normal or in the high 600s to low 700s... The broken ones seem to be around 40,000 to 50,000 or low numbers (possibly overflowing the u16?)...
